# Fixed version of your docker-compose.yml with Spark improvements

services:
  # PostgreSQL - Database for Dagster metadata
  postgres:
    image: postgres:15
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: dagster
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dagster"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ecommerce-network

  # pgAdmin - PostgreSQL administration and development platform
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ecommerce-pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ecommerce.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ecommerce-network

  # Zookeeper - Required for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: ecommerce-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper/data
      ZOOKEEPER_DATA_LOG_DIR: /var/lib/zookeeper/log
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    user: "0:0"
    networks:
      - ecommerce-network

  # Kafka - Message streaming platform
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: ecommerce-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ecommerce-network

  # Schema Registry - Kafka schema management
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    container_name: ecommerce-schema-registry
    depends_on:
      - kafka
    ports:
      - "8083:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8083
    networks:
      - ecommerce-network

  # Kafka UI - Web interface for Kafka management
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ecommerce-kafka-ui
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8083
    networks:
      - ecommerce-network

  # MinIO - S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: ecommerce-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ecommerce-network

  # MinIO Client - Initialize data lake bucket
  minio-init:
    image: minio/mc:latest
    container_name: ecommerce-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/data-lake --ignore-existing;
      echo 'MinIO data-lake bucket created successfully with organized subfolder structure';
      echo 'Structure: data-lake/{warehouse,bronze,silver,gold,checkpoints,logs,scripts}/';
      exit 0;
      "
    networks:
      - ecommerce-network

  # Spark Master - FIXED VERSION
  spark-master:
    image: bitnami/spark:3.5.0
    container_name: ecommerce-spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT_NUMBER=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      # Additional environment variables for better stability
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_HOME=/opt/bitnami/spark
    ports:
      - "7080:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master port
    volumes:
      - ./jars:/opt/bitnami/spark/jars-extra:rw
      - ./streaming:/opt/bitnami/spark/work-dir:rw
      - ./data:/opt/bitnami/spark/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080"] 
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-network

  # Spark Worker - FIXED VERSION
  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: ecommerce-spark-worker
    depends_on:
      spark-master:
        condition: service_started
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_WORKER_WEBUI_PORT=8081
      # Additional environment variables
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_HOME=/opt/bitnami/spark
    ports:
      - "8081:8081"  # Worker UI
    volumes:
      - ./jars:/opt/bitnami/spark/jars-extra:rw
      - ./streaming:/opt/bitnami/spark/work-dir:rw
      - ./data:/opt/bitnami/spark/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - ecommerce-network

  # Optional: Spark History Server for job monitoring
  spark-history:
    image: bitnami/spark:3.5.0
    container_name: ecommerce-spark-history
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=history
      - SPARK_HISTORY_UI_PORT=18080
      - SPARK_HISTORY_FS_LOG_DIRECTORY=/opt/bitnami/spark/logs
    ports:
      - "18080:18080"
    volumes:
      - ./spark-logs:/opt/bitnami/spark/logs:rw
    networks:
      - ecommerce-network

  # Dagster Daemon - Orchestration daemon
  dagster-daemon:
    build: 
      context: .
      dockerfile: Dockerfile.dagster.pyspark
    container_name: ecommerce-dagster-daemon
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DAGSTER_POSTGRES_USER: dagster
      DAGSTER_POSTGRES_PASSWORD: dagster
      DAGSTER_POSTGRES_DB: dagster
      DAGSTER_POSTGRES_HOST: postgres
      DAGSTER_POSTGRES_PORT: 5432
      DAGSTER_POSTGRES_URL: postgresql://dagster:dagster@postgres:5432/dagster
      DAGSTER_HOME: /opt/dagster/dagster_home
      # Java and Spark environment variables
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk-arm64
      SPARK_HOME: /opt/spark
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
    volumes:
      - ../:/opt/dagster/app
      - ./dagster/dagster_home:/opt/dagster/dagster_home
      - ./data:/opt/dagster/data
      - ../streaming:/opt/dagster/streaming
    command: ["dagster-daemon", "run", "-w", "/opt/dagster/dagster_home/workspace.yaml"]
    networks:
      - ecommerce-network

  # Dagster Webserver - Web UI
  dagster-webserver:
    build: 
      context: .
      dockerfile: Dockerfile.dagster.pyspark
    container_name: ecommerce-dagster-webserver
    depends_on:
      postgres:
        condition: service_healthy
      dagster-daemon:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: dagster
      DAGSTER_POSTGRES_PASSWORD: dagster
      DAGSTER_POSTGRES_DB: dagster
      DAGSTER_POSTGRES_HOST: postgres
      DAGSTER_POSTGRES_PORT: 5432
      DAGSTER_POSTGRES_URL: postgresql://dagster:dagster@postgres:5432/dagster
      DAGSTER_HOME: /opt/dagster/dagster_home
      # Java and Spark environment variables
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk-arm64
      SPARK_HOME: /opt/spark
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
    volumes:
      - ../:/opt/dagster/app
      - ./dagster/dagster_home:/opt/dagster/dagster_home
      - ./data:/opt/dagster/data
      - ./streaming:/opt/dagster/streaming
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-w", "/opt/dagster/dagster_home/workspace.yaml"]
    networks:
      - ecommerce-network

  # Iceberg REST Catalog - Metadata service for Iceberg tables
  iceberg-rest:
    image: tabulario/iceberg-rest:0.7.0
    container_name: ecommerce-iceberg-rest
    ports:
      - "8181:8181"
    environment:
      - CATALOG_WAREHOUSE=s3a://data-lake/warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_ACCESS__KEY__ID=minioadmin
      - CATALOG_S3_SECRET__ACCESS__KEY=minioadmin
      - CATALOG_S3_PATH__STYLE__ACCESS=true
    depends_on:
      - minio
    networks:
      - ecommerce-network

  # Trino - Distributed SQL query engine for Iceberg
  trino:
    image: trinodb/trino:435
    container_name: ecommerce-trino
    ports:
      - "8084:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/config.properties:/etc/trino/config.properties
    depends_on:
      - minio
      - iceberg-rest
    networks:
      - ecommerce-network
    environment:
      - JAVA_OPTS=-Xmx2G

  # Superset - Data visualization and exploration platform
  superset-db:
    image: postgres:15
    container_name: ecommerce-superset-db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - "5434:5432"
    volumes:
      - superset_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superset"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ecommerce-network

  superset:
    image: apache/superset:3.0.0
    container_name: ecommerce-superset
    depends_on:
      superset-db:
        condition: service_healthy
      trino:
        condition: service_started
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here_change_in_production
      - SUPERSET_ENV=production
      - DATABASE_DIALECT=postgresql
      - DATABASE_USER=superset
      - DATABASE_PASSWORD=superset
      - DATABASE_HOST=superset-db
      - DATABASE_PORT=5432
      - DATABASE_DB=superset
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - superset_home:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
      superset init &&
      gunicorn --bind 0.0.0.0:8088 --timeout 120 --workers 4 'superset.app:create_app()'
      "
    networks:
      - ecommerce-network

  # Redis - Cache for Superset
  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network


volumes:
  postgres_data:
  pgadmin_data:
  zookeeper_data:
  zookeeper_logs:
  kafka_data:
  minio_data:
  superset_db_data:
  superset_home:
  redis_data:

networks:
  ecommerce-network:
    driver: bridge
    name: ecommerce-analytics-network