# profiles.yml
ecommerce_analytics:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: ecommerce_user
      password: ecommerce_password
      port: 5432
      dbname: ecommerce_db
      schema: analytics_dev
      threads: 4
      keepalives_idle: 0

    prod:
      type: postgres
      host: localhost
      user: ecommerce_user
      password: ecommerce_password
      port: 5432
      dbname: ecommerce_db
      schema: analytics_prod
      threads: 8
      keepalives_idle: 0

    # Alternative: Use DuckDB for local development
    local:
      type: duckdb
      path: "/tmp/ecommerce_analytics.duckdb"
      schema: analytics
      threads: 4

  target: dev
