global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "spark-master"
    static_configs:
      - targets: ["spark-master:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "spark-worker"
    static_configs:
      - targets: ["spark-worker:8081"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9101"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "dagster"
    static_configs:
      - targets: ["dagster-webserver:3000"]
    metrics_path: "/metrics"
    scrape_interval: 60s
